z4_todoproject/todoapp/urls.py
from django.urls import path, include

from django.urls import path
from . import views


app_name='todoapp'

urlpatterns = [
    path('',views.add,name='add'),
    path('delete/<int:taskid>/',views.delete,name='delete'),
    path('update/<int:id>/', views.update, name='update'),
    path('cbvhome/',views.Tasklistview.as_view(),name='cbvhome'),
    path('cbvdetail/<int:pk>/',views.TaskDetailview.as_view(),name='cbvdetail'),
    path('cbvupdate/<int:pk>/', views.Taskupdateview.as_view(), name='cbvupdate'),
    path('cbvdelete/<int:pk>/', views.TaskDeleteView.as_view(), name='cbvdelete'),
    path('cbvcreate/', views.Taskcreateview.as_view(), name='cbvcreate')

]

z4_todoproject/z4_todoproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('',include('todoapp.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                           document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

z4_todoproject/todoapp/models.py
from django.db import models

# Create your models here.
class Task(models.Model):
    name=models.CharField(max_length=250)
    priority=models.IntegerField()
    date=models.DateField()

    def __str__(self):
        return self.name

z4_todoproject/todoapp/forms.py
from . models import Task
from django import forms

class TodoForm(forms.ModelForm):
    class Meta:
        model=Task
        fields=['name','priority','date']

z4_todoproject/todoapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse_lazy

from . models import Task
from . forms import TodoForm
from django.views.generic import ListView
from django.views.generic import DetailView
from django.views.generic.edit import UpdateView,DeleteView,CreateView
# Create your views here.

# views are two types function based and class based
class Tasklistview(ListView):
    model=Task
    template_name = 'home.html'
    context_object_name = 'task1'

class Taskcreateview(CreateView):
    model = Task
    template_name = 'home1.html'
    context_object_name = 'task1'
    fields = ('name', 'priority', 'date')
    success_url = reverse_lazy('todoapp:cbvhome')

class TaskDetailview(DetailView):
    model = Task
    template_name = 'detail.html'
    context_object_name = 'task'

class Taskupdateview(UpdateView):
    model = Task
    template_name = 'update.html'
    context_object_name = 'task'
    fields = ('name','priority','date')


    def get_success_url(self):
        return reverse_lazy('cbvdetail',kwargs={'pk':self.object.id})

class TaskDeleteView(DeleteView):
    model = Task
    template_name = 'delete.html'
    success_url = reverse_lazy('todoapp:cbvhome')


def add(request):
    task1 = Task.objects.all()
    if request.method=='POST':
        name=request.POST.get('name')
        priority=request.POST.get('priority')
        date=request.POST.get('date')
        task=Task(name=name,priority=priority,date=date)
        task.save()
    return render(request,'home.html',{'task1': task1})

# def details(request):
#
#     return render(request,'detail.html', )

def delete(request,taskid):
    task=Task.objects.get(id=taskid)
    if request.method=='POST':
        task.delete()
        return redirect('/')
    return render(request,'delete.html')

def update(request,id):
    task=Task.objects.get(id=id)
    f=TodoForm(request.POST or None,instance=task)
    if f.is_valid():
        f.save()
        return redirect('/')
    return render(request,'edit.html',{'f':f,'task':task})

z4_todoproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
{% block content %}
{% endblock %}
</body>
</html>

z4_todoproject/templates/delete.html
{% extends 'base.html' %}
{% block content %}
<form method="post">
    {% csrf_token %}
    <p>Are you sure this task is done?</p>
    <button type="submit">confirm</button>
</form>
{% endblock %}

z4_todoproject/templates/detail.html
{% extends 'base.html' %}
{% block content %}
 <div class="col-md-6">
            <div class="shadow card">
                <div class="card-body">
                    <h5 class="card-title">{{task.name}}</h5>
                    <p><b>{{task.priority}}</b></p>
                    <p><b>{{task.date}}</b></p>
                    <a class="btn btn-danger" href="{% url 'todoapp:delete' task.id %}">Done</a>
                    <a class="btn btn-warning" href="{% url 'todoapp:update' task.id %}">update</a>



                </div>
            </div>
            <br>

        </div>
{% endblock %}

z4_todoproject/templates/edit.html
{% extends 'base.html' %}
{% block content %}
<form method="post">
    {% csrf_token %}
  {{f.as_p}}
    <button type="submit">confirm</button>
</form>

{% endblock %}

z4_todoproject/templates/home.html
{% extends 'base.html' %}
{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="banner">
            <div class="banner-text">
                <p>ToDo</p>
            </div>
                </div>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
<!--    <div class="form-group">-->
         <div class="col-md-6">
    <form method="post" class="p-3 shadow">
    {% csrf_token %}

    <input type="text" name="name" class="form-control" placeholder="enter your task">
    <input type="number" name="priority" class="form-control" placeholder="enter your priority number">
       <input type="date" name="date" placeholder="enter the date">
        <input type="submit" class="btn btn-success">
    </form>
         </div>
        <div class="col-md-6">
            <h4>Task to be completed</h4>
            {% for i in task1 %}
            <div class="shadow card">
                <div class="card-body">
                    <h5 class="card-title">{{i.name}}</h5>
                    <p><b>{{i.priority}}</b></p>
                    <p><b>{{i.date}}</b></p>

                    <a class="btn btn-danger" href="{% url 'todoapp:delete' i.id %}">Done</a>
                    <a class="btn btn-warning" href="{% url 'todoapp:update' i.id %}">update</a>

                </div>
            </div>
            <br>
            {% endfor %}
        </div>
        </div>
    </div>
{% endblock %}

z4_todoproject/templates/home1.html
{% extends 'base.html' %}
{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="banner">
            <div class="banner-text">
                <p>ToDo</p>
            </div>
                </div>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
<!--    <div class="form-group">-->
         <div class="col-md-6">
    <form method="post" class="p-3 shadow">
    {% csrf_token %}

    <input type="text" name="name" class="form-control" placeholder="enter your task">
    <input type="number" name="priority" class="form-control" placeholder="enter your priority number">
       <input type="date" name="date" placeholder="enter the date">
       <a class="btn btn-danger" href="{% url 'todoapp:cbvcreate' %}">Submit=</a>
    </form>
         </div>
        <div class="col-md-6">
            <h4>Task to be completed</h4>
            {% for i in task1 %}
            <div class="shadow card">
                <div class="card-body">
                    <h5 class="card-title">{{i.name}}</h5>
                    <p><b>{{i.priority}}</b></p>
                    <p><b>{{i.date}}</b></p>

                    <a class="btn btn-danger" href="{% url 'todoapp:delete' i.id %}">Done</a>
                    <a class="btn btn-warning" href="{% url 'todoapp:update' i.id %}">update</a>

                </div>
            </div>
            <br>
            {% endfor %}
        </div>
        </div>
    </div>
{% endblock %}

z4_todoproject/templates/update.html
{% extends 'base.html' %}
{% block content %}

<div class="card">
    <div class="card-header">
        <div class="card-title">
            Task update
        </div>
        <div class="card-body">
            <form method="post">
                {% csrf_token %}
               {{form.as_p}}
             <button type="submit">confirm</button>
            </form>
        </div>
    </div>
</div>


{% endblock %}