z3_movieproject/movieapp/urls.py
from django.urls import path
from . import views
app_name='movieapp'

urlpatterns = [
    path('',views.index,name='index'),
    path('movie/<int:movie_id>/',views.detail,name='detail'),
    path('add/',views.add_movie,name='add_movie'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/',views.delete,name='delete')
]

z3_movieproject/z3_movieproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('',include("movieapp.urls"))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                           document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

z3_movieproject/movieapp/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    name = models.CharField(max_length=250)
    description = models.TextField()
    year = models.IntegerField()
    img= models.ImageField(upload_to='gallery')

    def __str__(self):
        return self.name

z3_movieproject/movieapp/forms.py
from django import forms
from . models import Movie
class MovieForm(forms.ModelForm):
    class Meta:
        model=Movie
        fields=['name','description','year','img']

z3_movieproject/movieapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from . models import Movie
from .forms import MovieForm
# Create your views here.
def index(request):
    movie=Movie.objects.all()
    context={
        'movie_list':movie
    }
    return render(request,'index.html',context)

def detail(request,movie_id):
    movie1=Movie.objects.get(id=movie_id)
    return render(request,'detail.html',{'movie1':movie1})

def add_movie(request):
    if request.method =='POST':
        name = request.POST.get('name')
        description = request.POST.get('description')
        year = request.POST.get('year')
        img = request.FILES['img']
        movie=Movie(name=name,description=description,year=year,img=img)
        movie.save()
    return render(request,'data.html')

def update(request,id):
    movie=Movie.objects.get(id=id)
    form=MovieForm(request.POST or None , request.FILES,instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'form':form,'movie':movie})

def delete(request,id):
    if request.method=='POST':
        movie=Movie.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request,'delete.html')

z3_movieproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css'%}">
</head>
<body>
<!-- Image and text -->
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">
    Movie Store
  </a>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

z3_movieproject/templates/data.html
{% extends 'base.html' %}
{% block body %}
<form method="post" action="" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" name="name" placeholder="enter movie name">
    <input type="text" name="description" placeholder="enter movie description">
    <input type="number" name="year" placeholder="enter movie year">
    <input type="file" name="img" >
    <input type="submit">

</form>
{% endblock %}

z3_movieproject/templates/delete.html
<form method="POST">
    {% csrf_token %}
    Are you want to delete this?
    <input type="submit">
</form>

z3_movieproject/templates/detail.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{movie1.img.url}}" width="300" height="300">
        </div>

<div class="col-md-6">
    <h4> {{movie1.name}}</h4><br>
    {{movie1.description}}<br>
    {{movie1.year}}<br>
    <a class="btn btn-warning" href="{% url 'movieapp:update' movie1.id %}">update</a>
    <a class="btn btn-danger" href="{% url 'movieapp:delete' movie1.id %}">delete</a>
</div>


</div>
</div>
{% endblock %}

z3_movieproject/templates/edit.html
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit">
</form>

z3_movieproject/templates/index.html
{% extends 'base.html' %}
{% block body %}

<div class="container">
    <div class="row">
        {% for i in movie_list %}
        <div class="col-md-3">
            <div class="card" >
                <img class="card-img-top" src="{{i.img.url}}"   height="250px"  alt="">
  <div class="card-body">
      <h5 class="card-title">{{i.name}}</h5>
<!--    <p class="card-text">{{i.description}}</p>-->
    <a href="{% url 'movieapp:detail' i.id %}" class="btn btn-warning">View Details</a>
  </div>
</div>
        </div>
        {% endfor %}


    </div>
     <a href="{% url 'movieapp:add_movie' %}" class="btn btn-danger" >add </a>

</div>
{% endblock %}

<!--{{i.id}}-&ndash;&gt;{{i.name}}&ndash;&gt;{{i.description}}-&ndash;&gt;{{i.year}}<br>-->
<!--using link-->
<!--<a href="movie/{{i.id}}">{{i.name}}<br>-->
<!--<img src="{{i.img.url}}" width="100" height="100">-->
<!--<a href="{% url 'movieapp:detail' i.id %}">{{i.name}}<br>-->
<!--</a>-->